# Generated by Django 4.2.27 on 2026-02-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên cửa hàng")),
                ("address", models.CharField(max_length=500, verbose_name="Địa chỉ")),
                ("phone", models.CharField(max_length=20, verbose_name="Điện thoại")),
                ("latitude", models.FloatField(verbose_name="Vĩ độ (Lat)")),
                ("longitude", models.FloatField(verbose_name="Kinh độ (Lon)")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên váy")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Giá thuê"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.store",
                        verbose_name="Thuộc cửa hàng",
                    ),
                ),
            ],
        ),
    ]
