# Generated by Django 4.2.27 on 2026-01-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên loại váy")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Tên chi nhánh"),
                ),
                (
                    "address",
                    models.CharField(max_length=500, verbose_name="Địa chỉ cụ thể"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Số điện thoại"),
                ),
                ("latitude", models.FloatField(verbose_name="Vĩ độ (Lat)")),
                ("longitude", models.FloatField(verbose_name="Kinh độ (Lon)")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên váy")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Giá thuê (VND)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Ảnh minh họa",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Chi tiết sản phẩm"),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Còn hàng"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.category",
                        verbose_name="Loại váy",
                    ),
                ),
            ],
        ),
    ]
