# Generated by Django 4.2.27 on 2026-02-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Tên khách"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Số điện thoại"),
                ),
                ("booking_date", models.DateTimeField(verbose_name="Ngày giờ hẹn")),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú thêm"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ duyệt"),
                            ("confirmed", "Đã duyệt"),
                            ("done", "Đã xong"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đặt"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                        verbose_name="Váy muốn thử",
                    ),
                ),
            ],
        ),
    ]
