# Generated by Django 4.2.27 on 2026-03-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="stores/",
                verbose_name="Ảnh đại diện tiệm",
            ),
        ),
    ]
