# Generated by Django 4.2.27 on 2026-03-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_store_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="store_images/"),
        ),
    ]
