# Generated by Django 4.2.27 on 2026-04-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_store_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Tồn kho"),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Sẵn sàng"),
                    ("rented", "Đang thuê"),
                    ("washing", "Đang giặt"),
                ],
                default="available",
                max_length=20,
                verbose_name="Tình trạng",
            ),
        ),
    ]
