# Generated by Django 4.2.27 on 2026-04-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_product_quantity_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="address",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Địa chỉ giao váy"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Vĩ độ (Lat)"),
        ),
        migrations.AddField(
            model_name="booking",
            name="longitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Kinh độ (Lon)"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="Phí ship"
            ),
        ),
    ]
