# Generated by Django 4.2.27 on 2026-04-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_booking_address_booking_latitude_booking_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="product",
        ),
        migrations.AddField(
            model_name="booking",
            name="products",
            field=models.ManyToManyField(
                to="store.product", verbose_name="Các váy muốn thử"
            ),
        ),
    ]
