# Generated by Django 4.2.27 on 2026-04-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
