# Generated by Django 4.2.27 on 2026-05-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_product_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about_icons/",
                        verbose_name="Icon",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Tiêu đề thẻ")),
                ("description", models.TextField(verbose_name="Mô tả chi tiết")),
            ],
            options={
                "verbose_name": "Tiêu chí nổi bật",
                "verbose_name_plural": "Các tiêu chí nổi bật",
            },
        ),
        migrations.CreateModel(
            name="AboutUsContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_title",
                    models.CharField(
                        default="Câu Chuyện Của Chúng Tôi",
                        max_length=255,
                        verbose_name="Tiêu đề chính",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        default="Nơi những giấc mơ lấp lánh hóa thành hiện thực...",
                        max_length=500,
                        verbose_name="Slogan",
                    ),
                ),
                (
                    "origin_title",
                    models.CharField(
                        default="Khởi Nguồn Của Cái Đẹp",
                        max_length=255,
                        verbose_name="Tiêu đề Khởi Nguồn",
                    ),
                ),
                (
                    "origin_content",
                    models.TextField(verbose_name="Nội dung Khởi Nguồn"),
                ),
                (
                    "origin_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about_images/",
                        verbose_name="Ảnh cô dâu",
                    ),
                ),
                (
                    "tech_title",
                    models.CharField(
                        default="Cảm Xúc Giao Thoa Công Nghệ",
                        max_length=255,
                        verbose_name="Tiêu đề Công Nghệ",
                    ),
                ),
                ("tech_content", models.TextField(verbose_name="Nội dung phần GIS")),
                (
                    "tech_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about_images/",
                        verbose_name="Ảnh bản đồ",
                    ),
                ),
                (
                    "tech_quote",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Câu Quote"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nội dung trang giới thiệu",
                "verbose_name_plural": "Nội dung trang giới thiệu",
            },
        ),
    ]
