"""
Django settings for vaycuoigis project.

Generated by 'django-admin startproject' using Django 4.2.27.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-72h212q^-h#g9h36#jp)wr$_-ecwqris5m)#z1mk&rkzxb8&=*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",  # Jazzmin PHẢI đứng trước admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "store",  # App quản lý Store và Product của bạn
    'django.contrib.humanize',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vaycuoigis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'], # Kết nối thư mục templates chứa HTML
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vaycuoigis.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "vaycuoigis",       # Tên Database
        "USER": "postgres",         # User Postgres
        "PASSWORD": "123456",       # Mật khẩu Postgres
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "vi"  # Tiếng Việt

TIME_ZONE = "Asia/Ho_Chi_Minh" # Giờ Việt Nam

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Đường dẫn thư mục Static (CSS, JS)
# Đảm bảo bạn đã tạo file: vaycuoigis/static/css/admin_royal.css
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# --- CẤU HÌNH MEDIA (Lưu ảnh váy cưới) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ==============================================
# CẤU HÌNH GIAO DIỆN QUẢN TRỊ (JAZZMIN) - ROYAL THEME
# ==============================================

JAZZMIN_SETTINGS = {
    # Tiêu đề Tab trình duyệt
    "site_title": "Quản trị Váy Cưới GIS",
    
    # Tiêu đề chính trên thanh Navbar
    "site_header": "Bridal Admin",
    
    # Tên thương hiệu hiển thị ở Sidebar
    "site_brand": "Bridal Luxury",
    
    # Thông điệp chào mừng
    "welcome_sign": "Chào mừng đến với hệ thống quản trị Váy Cưới",
    "copyright": "Bridal GIS Team",
    
    # --- QUAN TRỌNG: Kết nối file CSS tùy chỉnh ---
    # File này phải nằm tại: static/css/admin_royal.css
    "custom_css": "css/admin_royal.css",

    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Icon cho Menu (FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "store.Product": "fas fa-female",   # Icon Cô dâu/Váy
        "store.Store": "fas fa-store-alt",  # Icon Cửa hàng
    },
}

JAZZMIN_UI_TWEAKS = {
    # 1. Theme nền tảng: Flatly (Phẳng, sáng, dễ tùy chỉnh màu)
    "theme": "flatly",
    
    # 2. Sidebar: Light (Sáng) - Để CSS của chúng ta biến nó thành trắng tinh
    "sidebar": "sidebar-light-primary", 
    
    # 3. Navbar: Dark (Để chữ màu trắng) - CSS của chúng ta sẽ biến nền thành màu Hồng
    "navbar": "navbar-dark",
    
    # 4. Các tùy chỉnh khác
    "accent": "accent-primary",
    "brand_colour": "navbar-primary",
    
    "no_navbar_border": True,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    
    # Class Bootstrap cho các nút bấm
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}