"""
Django settings for vaycuoigis project.

Generated by 'django-admin startproject' using Django 4.2.27.
"""

from pathlib import Path
import os  # Thêm thư viện os để xử lý đường dẫn

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-72h212q^-h#g9h36#jp)wr$_-ecwqris5m)#z1mk&rkzxb8&=*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "store",  # App quản lý Store và Product của bạn
    'django.contrib.humanize',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vaycuoigis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'], # Kết nối thư mục templates chứa HTML
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vaycuoigis.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# --- CẤU HÌNH POSTGRESQL (Theo yêu cầu của thầy) ---
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "vaycuoigis",       # Tên Database bạn tạo trong Postgres
        "USER": "postgres",         # User mặc định (hoặc tên máy Mac của bạn)
        "PASSWORD": "123456",          # Mật khẩu Postgres của bạn (Nhớ sửa lại nếu khác)
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "vi"  # Tiếng Việt

TIME_ZONE = "Asia/Ho_Chi_Minh" # Giờ Việt Nam

USE_I18N = True

USE_TZ = True

USE_L10N = True
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Đường dẫn thư mục Static (CSS, JS)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# --- CẤU HÌNH MEDIA (QUAN TRỌNG ĐỂ LƯU ẢNH VÁY CƯỚI) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# --- CẤU HÌNH BỔ SUNG CHO JAZZMIN (Tùy chọn nhưng nên có) ---
JAZZMIN_SETTINGS = {
    "site_title": "Hệ thống Váy Cưới GIS",
    "site_header": "Váy Cưới GIS",
    "site_brand": "Quản trị Váy Cưới",
    "welcome_sign": "Chào mừng bạn đến với hệ thống quản lý Váy Cưới",
    "search_model": ["store.Product", "store.Booking"],
    "topmenu_links": [
        {"name": "Trang chủ", "url": "home", "permissions": ["auth.view_user"]},
    ],
    "show_ui_builder": True, # Bật cái này để bạn tự chỉnh màu sắc giao diện Admin theo ý thích
}

JAZZMIN_UI_CONFIG = {
    "theme": "flatly", # Bạn có thể đổi sang 'lux', 'pulse', hoặc 'simplex'
}